import Zoo

#print axioms Zoo.Tortoise.split_reconstructs
#print axioms Zoo.Tortoise.train_precedes_test
#print axioms Zoo.Owl.output_length
#print axioms Zoo.Owl.valid_column_count
#print axioms Zoo.Owl.report_requires_freeze
#print axioms Zoo.Octopus.output_length
#print axioms Zoo.Octopus.valid_column_count
#print axioms Zoo.Octopus.report_requires_freeze
#print axioms Zoo.Gecko.output_length
#print axioms Zoo.Gecko.valid_column_count
#print axioms Zoo.Gecko.report_requires_freeze
#print axioms Zoo.Hive.output_length
#print axioms Zoo.Hive.valid_column_count
#print axioms Zoo.Hive.report_requires_freeze
#print axioms Zoo.Eagle.output_length
#print axioms Zoo.Eagle.valid_column_count
#print axioms Zoo.Eagle.report_requires_freeze
#print axioms Zoo.Crab.output_length
#print axioms Zoo.Crab.valid_column_count
#print axioms Zoo.Crab.report_requires_freeze
#print axioms Zoo.Shepherd.output_length
#print axioms Zoo.Shepherd.valid_column_count
#print axioms Zoo.Shepherd.report_requires_freeze
#print axioms Zoo.Pulse.output_length
#print axioms Zoo.Pulse.valid_column_count
#print axioms Zoo.Pulse.report_requires_freeze
#print axioms Zoo.Cat.positive_removal_hurt
#print axioms Zoo.Cat.removal_hurts_iff
#print axioms Zoo.Fox.output_length
#print axioms Zoo.Fox.valid_column_count
#print axioms Zoo.Fox.report_requires_freeze
#print axioms Zoo.Spider.output_length
#print axioms Zoo.Spider.valid_column_count
#print axioms Zoo.Spider.report_requires_freeze
#print axioms Zoo.Raven.output_length
#print axioms Zoo.Raven.valid_column_count
#print axioms Zoo.Raven.report_requires_freeze
#print axioms Zoo.Dolphin.output_length
#print axioms Zoo.Dolphin.valid_column_count
#print axioms Zoo.Dolphin.report_requires_freeze
#print axioms Zoo.Ant.output_length
#print axioms Zoo.Ant.valid_column_count
#print axioms Zoo.Ant.report_requires_freeze
#print axioms Zoo.Moth.output_length
#print axioms Zoo.Moth.valid_column_count
#print axioms Zoo.Moth.report_requires_freeze
#print axioms Zoo.Shark.output_length
#print axioms Zoo.Shark.valid_column_count
#print axioms Zoo.Shark.report_requires_freeze
#print axioms Zoo.Penguin.output_length
#print axioms Zoo.Penguin.valid_column_count
#print axioms Zoo.Penguin.report_requires_freeze
#print axioms Zoo.Bat.placebo_has_priority
#print axioms Zoo.Hedgehog.heldout_not_development
#print axioms Zoo.Crocodile.common_shift_cancels
#print axioms Zoo.Crocodile.causal_requires_design
#print axioms Zoo.Dragon.output_length
#print axioms Zoo.Dragon.valid_column_count
#print axioms Zoo.Dragon.report_requires_freeze
#print axioms Zoo.Turtle.applicable_veto_blocks_support
#print axioms Zoo.Turtle.empty_is_insufficient
#print axioms Zoo.Magpie.no_history_no_alarm
#print axioms Zoo.Wolf.alarm_requires_distributed_support
#print axioms Zoo.Elephant.current_members_active
#print axioms Zoo.Elephant.zero_fuel_stops
#print axioms Zoo.Chameleon.excess_nonnegative
#print axioms Zoo.Chameleon.expected_explains
#print axioms Zoo.Jellyfish.node_count_preserved
#print axioms Zoo.Beaver.accepted_requires_rollback
#print axioms Zoo.Beaver.accepted_requires_bounds
#print axioms Zoo.Mantis.unready_calibrates
#print axioms Zoo.Bison.queue_bounded
#print axioms Zoo.Weasel.retained_within_budget
#print axioms Zoo.Salmon.exhaustion_not_origin
#print axioms Zoo.Orca.complete_requires_ack
#print axioms Zoo.Mole.no_indicators_no_failure_claim
#print axioms Zoo.Lynx.emergent_requires_replication
#print axioms Zoo.Horse.handoff_retains_uncertainty
#print axioms Zoo.Termite.population_preserved
#print axioms Zoo.Phoenix.stable_requires_every_checkpoint
#print axioms Zoo.Cobra.nonimproving_proxy_zero
#print axioms Zoo.Whale.empty_history_zero_gap
#print axioms Zoo.Falcon.positive_margin_iff_on_time
#print axioms Zoo.Falcon.absent_alarm_no_timing
#print axioms Zoo.Rhino.survives_selected_invariant
#print axioms Zoo.Bonobo.mutual_gain_excludes_loser
#print axioms Zoo.Axolotl.acceptable_retains_invariants
#print axioms Zoo.Butterfly.run_records_initial_and_steps
#print axioms Zoo.admissible_no_leakage
#print axioms Zoo.not_admissible_if_unfrozen
#print axioms Zoo.rankScores_length
#print axioms Zoo.firstIndex_nil
#print axioms Zoo.hasVeto_cons
#print axioms Zoo.memoryNumerator_sign
#print axioms Zoo.memoryNumerator_zero
#print axioms Zoo.Registry.exactly_forty_six
#print axioms Zoo.Registry.no_duplicate_animals
#print axioms Zoo.Registry.names_match_count
